.TH "fmanager::createDirectory" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"
.SH "Description"
.SS \fBint fmanager::createDirectory(\fIconst string& dirname\fP)\fP
creates a directory
.SH "Parameters"
.SS \fIconst string& dirname\fP
directory path relative to \fIgetLDir()\fP or last \fIchangeDirectory()\fP call, or full path
.SH "Return value"
returns 0 on success or 1 on failure
