.TH "fmanager::splitFilePart" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"
.SH "Description"
.SS \fB\fIint\fP fmanager::splitFilePize(\fIconst string& fname\fP, \fIconst string& ofname\fP, \fIconst int& parts\fP)\fP
.SH "Parameters"
.SS \fIconst string& fname\fP
file to split, relative path to \fIgetLDir()\fP or last \fIchangeDirectory()\fP if ever called, or full path
.SS \fIconst string& ofname\fP
output file prefix to merge, relative path to \fIgetLDir()\fP or last \fIchangeDirectory()\fP if ever called, or full path, \fBnote that splitted files will suffix of the split piece number\fP.
.SS \fIconst int& size\fP
count of splitted files
.SH "Return value"
returns 0 on success or 1 on failure
.SH "See also"
\fBfmanager_splitFilePart(1)\fP, \fBfmanager_splitSize(1)\fP
