.TH "fmanager::getChildPath" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"
.SH "Description"
.SS \fBstring fmanager::getChildPath(\fIconst string& path\fP)\fP
gets lowest level node of a given path
.SH "Parameters"
.SS \fIconst string& path\fP
full directory path
.SH "Return value"
returns lowest level path or the given string with appended path delimeter
.SH "Example code"

.nf
.RS
\fB
fmanager* fm = new fmanager("fm");
cout << fm\->getTopPath("c:\\\\program files\\\\mozilla\\\\") << endl;
cout << fm\->getTopPath("/etc");
OUTPUT:
mozilla\\
etc/
\fP
.fi
.RE
