.TH "fmanager::listDirectory" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"
.SH "Description"
.SS \fB\fIvector<FINFO*>*\fP fmanager::listDirectory(\fIconst string& dir\fP, \fIconst bool& recursive\fP, \fIconst bool& skipPermission\fP, \fIconst string& date\fP)\fP

lists a directory entries
.SH "Parameters"
.SS \fIconst string& dir\fP
directory path relative to \fIgetLDir()\fP or last call to \fIchangeDirectory()\fP or full path
.SS \fIconst bool& recursive\fP
list all entries recursively
.SS \fIconst bool& skipPermission\fP
ignore access permission errors
.SS \fIconst string& date\fP
date type, gmt or local
.SH "Return value"
returns a pointer to a heap allocaed \fIstd::vector<FINFO*>*\fP if there is any results or \fINULL\fP on failure
.SH "See also"
\fBfmanager::FINFO(3)\fP
