.TH "fmanager::checkAvailable" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"
.SH "Description"
.SS \fBint fmanager::checkAvailable(const string& name)\fP
check if a file/directory is present or not.
.SH "Parameters"
.SS \fBconst string& name\fP
a \fIstd::string\fP with the name of the file/directory to be checked for.
.SH "Return value"
return 0 on success or 1 on failure.
