.TH "libfmanager" 3 "16 August 2009" "AbdAllah Aly Saad" "pre-alpha 0.10"

.SH NAME
fmanager - C++ class library for file management
.SH LIBRARY
fmanager - (-lfmanager)
.SH SYNOPSIS
#include <fmanager.hpp>
.SH DESCRIPTION
.B fmanager\c
is a class library for file management ( create, delete or modify both files and directories)
.B fmanager \c is available for both linux ( POSIX complaint ) and microsoft windows
.TP
.I EBADF
fd is not a valid file descriptor.
.TP
.I EINVAL
fd is unsuitable for reading
